name: Create new sandbox-access-form release package

on:
  push:
    branches: [main]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --tags origin

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Get current hash
        run: git log

      - name: Run Build
        run: npm run build
      
      # - name: Show build results
      #   run: |
      #     ls -la ./
      #     ls -la ./lib

      - name: Create archive tarball
        run: |
          ls -la ./lib
          tar -cf ./release.tar.bz2 lib package.json
          mkdir testing
          cp ./release.tar.bz2 testing/release.tar.bz2
          cd testing
          tar -xf release.tar.bz2
          ls -la ./
          ls -la ./lib

      - name: Create the release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          RELEASE_TITLE=`gh api /repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA | jq -r '.commit.message' | head -1`
          echo $RELEASE_TITLE
          # If the commit message doesn't include the PR number at the end, append it.
          if ! [[ $RELEASE_TITLE =~ \(\#[0-9]\) ]]; then
            echo "PR number missing. This will append it to the release title."
            PR_NUMBER=`gh api -X GET search/issues -f q="$GITHUB_SHA" | jq -r '.items[0].number'`
            echo $PR_NUMBER;
            RELEASE_TITLE="$RELEASE_TITLE (#$PR_NUMBER)"
            echo $RELEASE_TITLE;
          fi
          NEW_TAG=$(git tag --sort=-creatordate | head -1 | awk -F. -v OFS=. '{$NF++;print}')
          echo $NEW_TAG;
          gh release create $NEW_TAG --title="$RELEASE_TITLE"
          gh release upload $NEW_TAG "release.tar.bz2#${NEW_TAG}.tar.bz2"
